;; Triangle, pentagonal, and hexagonal numbers are generated by the following
;; formulae:
;;
;; Triangle   Tn=n(n+1)/2  1, 3, 6, 10, 15, ...
;; Pentagonal Pn=n(3n−1)/2 1, 5, 12, 22, 35, ...
;; Hexagonal  Hn=n(2n−1)   1, 6, 15, 28, 45, ...
;; It can be verified that T285 = P165 = H143 = 40755.
;;
;; Find the next triangle number that is also pentagonal and hexagonal.

(load "util")

(defn pentagonal? [n]
  (integral? (/ (inc (Math/sqrt (inc (* 24 n)))) 6)))

(def hexagonal-numbers
  (map #(* % (dec (* 2 %))) (iterate inc 1)))

(defn euler-45 [n]
  (nth (filter pentagonal? hexagonal-numbers) (dec n)))

(run (euler-45 3))
